import React from "react";
import Head from "next/head";
import { Earth } from "../modules/Home/earth";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Earth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Earth />
    </div>
  );
}
