import React from "react";
import Head from "next/head";
import { SphereModel } from "../modules/Home/sphere_model";
import styles from "../styles/Home.module.css";
import { NavigationLeft } from "../modules/Home/component.navigation_left";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.leftSectionContainer}>
        <div className={styles.contents}>
          <NavigationLeft />
        </div>
      </section>
      <section className={styles.sphereSectionContainer}>
        <SphereModel />
      </section>
      <section className={styles.rightSectionContainer}></section>
    </div>
  );
}
